# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9f035dce44ce1a3f95b8316c2db3185326e89f67118e2ebf6a259826393b27e8848af26f0888e3d5d7941b2c14077b008bb0f270ed22e1016dce69ccf2fa70cf

test:
  secret_key_base: 46f5c0be6e926807f283135d142e8c9013a3839266e70ffadb74e43c3d2ceed461ceff61e222e2e52c07e2761d2e81082a958dc63e1943e647b17f2fb2cda949

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
